### ISSUE TITLE
Rule34.xxx no longer loading images

### ISSUE THREAD

**Issue by Baggytrousers27** [flexbooru/flexbooru#233]
Rule34.xxx's gallery no longer populates as of a week ago. Refreshed the page and suddenly all the images vanished

Using the config provided on the [io page](https://flexbooru.github.io/flexbooru/config.html) the posts tab remains blank, the tags tab provides an error 301 and the search bar doesn't provide tag suggestions.

**Screenshots**
![397100390_699592882114400_6663923327437298803_n](https://github.com/flexbooru/flexbooru/assets/15883796/f3b1bad6-e9f8-4fb4-845f-af30322fdeb2)

![397100382_1449762908913767_5358358463177979589_n](https://github.com/flexbooru/flexbooru/assets/15883796/8575043d-9288-4cbb-8418-2b43e6808101)

 - Device name: [Galaxy Note 20 Ultra 5G]
 - OS version: [Android 13]
 - App version [3.2.1.c1357]

**Comment by kotoshii** [comment]
Same shit

**Comment by kotoshii** [comment]
@Baggytrousers27 I found the solution. You need to update your rule34 host from rule34.xxx to api.rule34.xxx in config.
cc @onlymash

**Comment by rewqazxv** [comment]
Sorry, this is caused by 
https://github.com/flexbooru/flexbooru/blob/45db07498fbc823a743c27a0b2b73f1c2b51378d/android/src/main/java/onlymash/flexbooru/data/api/ApiExt.kt#L52-L55
I removed redirection for Gelbooru because it will jump to the home page and waste about 11KB every time you click the unfavorite button, but i didn't notice that the optimization also affects Rule34 which uses redirection to use its api.
